[versions]
version = "3.5.8.2-SNAPSHOT"
spring-boot-dependencies = "3.5.8"
spring-cloud-dependencies = "2025.0.0"
spring-cloud-alibaba-dependencies = "2025.0.0.0-preview"

springdoc-openapi-bom = "2.8.12"
spring-ai-bom = "1.0.1"
spring-statemachine = "4.0.1"
context-propagation = "1.2.0"
guava = "33.5.0-jre"
jspecify = "1.0.0"
commons-lang3 = "3.20.0"
commons-collections4 = "4.5.0"
commons-compress = "1.28.0"
commons-pool2 = "2.12.1"
commons-text = "1.14.0"
commons-csv = "1.14.1"
commons-codec = "1.20.0"
commons-io = "2.21.0"
commons-net = "3.12.0"
vavr = "0.10.6"
bcprov-jdk18on = "1.83"
mapstruct = "1.6.3"
lombok-mapstruct-binding = "0.2.0"
hypersistence-utils-hibernate = "3.12.0"
zstd-jni = "1.5.7-6"
xz = "1.11"
jetbrains-annotations = "26.0.2-1"
jmh = "1.37"
jimmer-bom = "0.9.113"
jimmer-ddl = "0.3.0"
okhttp3 = "5.3.2"
aws-sdk = "2.36.1"

junit-bom = "5.13.1"

multi-release-jar = "0.1.1"

[libraries.jspecify]
module = "org.jspecify:jspecify"
version.ref = "jspecify"

[libraries.spring-statemachine]
module = "org.springframework.statemachine:spring-statemachine-core"
version.ref = "spring-statemachine"

[libraries.io-micrometer-context-propagation]
module = "io.micrometer:context-propagation"
version.ref = "context-propagation"

[libraries.guava]
module = "com.google.guava:guava"
version.ref = "guava"

# Apache org.apache.commons
[libraries.commons-lang3]
module = "org.apache.commons:commons-lang3"
version.ref = "commons-lang3"

[libraries.commons-collections4]
module = "org.apache.commons:commons-collections4"
version.ref = "commons-collections4"

[libraries.commons-compress]
module = "org.apache.commons:commons-compress"
version.ref = "commons-compress"

[libraries.commons-pool2]
module = "org.apache.commons:commons-pool2"
version.ref = "commons-pool2"

[libraries.commons-text]
module = "org.apache.commons:commons-text"
version.ref = "commons-text"

[libraries.commons-csv]
module = "org.apache.commons:commons-csv"
version.ref = "commons-csv"

[libraries.commons-codec]
module = "commons-codec:commons-codec"
version.ref = "commons-codec"

[libraries.commons-io]
module = "commons-io:commons-io"
version.ref = "commons-io"

[libraries.commons-net]
module = "commons-net:commons-net"
version.ref = "commons-net"

[libraries.vavr]
module = "io.vavr:vavr"
version.ref = "vavr"

[libraries.bcprov-jdk18on]
module = "org.bouncycastle:bcprov-jdk18on"
version.ref = "bcprov-jdk18on"

[libraries.mapstruct-very]
module = "org.mapstruct:mapstruct"
version.ref = "mapstruct"

[libraries.mapstruct-jdk8]
module = "org.mapstruct:mapstruct-jdk8"
version.ref = "mapstruct"

[libraries.mapstruct-processor]
module = "org.mapstruct:mapstruct-processor"
version.ref = "mapstruct"

[libraries.lombok-mapstruct-binding]
module = "org.projectlombok:lombok-mapstruct-binding"
version.ref = "lombok-mapstruct-binding"

[libraries.hypersistence-utils-hibernate-63]
module = "io.hypersistence:hypersistence-utils-hibernate-63"
version.ref = "hypersistence-utils-hibernate"

[libraries.zstd-jni]
module = "com.github.luben:zstd-jni"
version.ref = "zstd-jni"

[libraries.xz]
module = "org.tukaani:xz"
version.ref = "xz"

[libraries.jetbrains-annotations]
module = "org.jetbrains:annotations"
version.ref = "jetbrains-annotations"

[libraries.jmh-core]
module = "org.openjdk.jmh:jmh-core"
version.ref = "jmh"

[libraries.jmh-annotation-processor]
module = "org.openjdk.jmh:jmh-generator-annprocess"
version.ref = "jmh"

[libraries.okhttp3]
module = "com.squareup.okhttp3:okhttp"
version.ref = "okhttp3"

[libraries.jimmer-apt]
module = "io.github.honhimw:jimmer-apt"
version.ref = "jimmer-bom"

[libraries.jimmer-ddl]
module = "io.github.honhimw:jimmer-ddl"
version.ref = "jimmer-ddl"

[libraries.junit-bom]
module = "org.junit:junit-bom"
version.ref = "junit-bom"

[plugins.multi-release-jar]
id = "me.champeau.mrjar"
version.ref = "multi-release-jar"
